// update highscores 
if global.maxKills <= global.kills global.maxKills = global.kills
if global.lastScore >=  global.kills global.last = global.kills

//scrWrite() // better against a server
   
STEP = 12
FIRST_STEP = 300;
SECOND_STEP = 595;
INTERLUDE = 399;

FIRST_ROW_HEIGHT = 0.53;
SECOND_ROW_HEIGHT = 0.61;

WIDTH_OFFSET = 0.25;
HEIGHT_OFFSET = 0.45;

WEAPON_FRAME_GAP = 128;
OFFSET_WEAPON_FRAME = 0.80;
FRAME_FLICK_SPEED = 1.05;

//script para mostrar interludio
t= 0
vText = "KILLS 999"
iText = 1; //This variable controls how many letters are currently shown (e.g. if iText = 8 then the first 8 letters of vText will be shown
alarm[0] = 1; //Here we set the whole script in motion

//textos marquesina
scroll = 0
marqueText [0] = " WHITE BLOCK WHITE BLOCK WHITE BLOCK WHITE BLOCK WHITE BLOCK WHITE BLOCK WHITE BLOCK WHITE BLOCK WHITE BLOCK WHITE BLOCK WHITE BLOCK "
marqueText [1] = " LASER  LASER LASER LASER LASER LASER LASER LASER LASER LASER LASER LASER LASER LASER LASER LASER LASER LASER LASER LASER LASER LASER "
marqueText [2] = " 3 WAY 3 WAY 3 WAY 3 WAY 3 WAY 3 WAY 3 WAY 3 WAY 3 WAY 3 WAY 3 WAY 3 WAY 3 WAY 3 WAY 3 WAY 3 WAY 3 WAY 3 WAY 3 WAY 3 WAY 3 WAY 3 WAY 3 WAY 3 WAY 3 WAY 3 WAY 3 WAY 3 WAY "
marqueText [3] = " CIRCLE CIRCLE CIRCLE CIRCLE CIRCLE CIRCLE CIRCLE CIRCLE CIRCLE CIRCLE CIRCLE CIRCLE CIRCLE CIRCLE CIRCLE CIRCLE CIRCLE CIRCLE CIRCLE "
marqueText [4] = " TRIANGLE OF DESTRUCTION TRIANGLE OF DESTRUCTION TRIANGLE OF DESTRUCTION TRIANGLE OF DESTRUCTION TRIANGLE OF DESTRUCTION TRIANGLE OF DESTRUCTION "
marqueText [5] = " RAYS RAYS RAYS RAYS RAYS RAYS RAYS RAYS RAYS RAYS RAYS RAYS RAYS RAYS RAYS RAYS RAYS RAYS RAYS RAYS RAYS RAYS RAYS RAYS RAYS RAYS RAYS RAYS RAYS "
marqueText [6] = "SDF"
marqueText [7] = "SDF"


